### ISSUE TITLE
[구상] 공격/방어에 공통. 맵 밖으로 나갔을때 어떻게 돌아올까요?

### ISSUE THREAD

**Issue by lukepark327** [fuzzythecat/OceanView#12]
공격과 방어모드에 구분 없이 적용할 수 있을 것 같습니다. 

단순히 방향을 180도 틀어 되돌아가는 방법은 어떨지 모르겠네요

**Comment by fuzzythecat** [comment]
우리 로봇이 맵 밖에 위치할 때, 
상대방 로봇이 미친척하고 달려와서 우리를 치는 경우는 없을까요?

**Comment by lukepark327** [comment]
우리가 공격모드일 경우에는 상대가 방어모드이기 때문에 고려하지 않아도 될 것 같네요.

방어 모드일때는, 우리 로봇이 time out되는 시간은 10초, 상대방은 8초라서 들어오지 못하게 하려고 오는
경우는 없을 것 같네요

**Comment by tkddus121** [comment]
단순이 직선운동 하지말고 
원을 그리면서? 반경을 점점 키워가며 맵에 돌아올 때 까지 뱅뱅 도는 것도 괜찮을 것 같습니다.

**Comment by fuzzythecat** [comment]
아 그러면 반드시 돌아올 것 같네요.
좋은 생각 같아요~ 이대로 구현 이슈 만들겠습니다.
