### ISSUE TITLE
[2차구현] 이거 바꿔야 될것같은데

### ISSUE THREAD

**Issue by tkddus121** [fuzzythecat/OceanView#19]
이거 내가 구현 해보니까
경계선 따라서 돌아다니는거 못만들것같어

작년에는 라인트레이서 하나로 한학기 프로젝트가 진행됐는데
그거에+추가구현인 셈이라...

**Comment by tkddus121** [comment]
그리고 지금은 터치센서가 쓸모가 없어서 구조도 바꿔야될것같어

**Comment by fuzzythecat** [comment]
자바마스터께서 그러신다면...

터치센서 그러면 뒤에다 달아놓고 
작동하면 90도정도 방향 틀어서 움직이는거 어때
소나센서로 감지하기 힘들것같은데

**Comment by fuzzythecat** [comment]
아 센서 다른조도 하나씩 쓰니까 
그냥 방향을 계속 틀면서 돌아다니는거 어떰

**Comment by tkddus121** [comment]
소나센서로는 앞에 장애물 감지되면 방향 틀어서 도망가는거는 구현할 수 있을듯한데

**Comment by fuzzythecat** [comment]
ㅋㅋ오키 문서 업데이트할테니까 보고 구현해줘
이해안가는거있으면 톡 고고

**Comment by fuzzythecat** [comment]
머지완료~
