### ISSUE TITLE
[1차 구상] 알고리즘을 구상합시다

### ISSUE THREAD

**Issue by fuzzythecat** [fuzzythecat/OceanView#5]
Wiki 페이지의 방어모드의 승리조건을 기준으로, 
어떤 알고리즘을 만들어야 이길 수 있을까요?

**Comment by fuzzythecat** [comment]
소나와 터치 센서는 각각 하나씩만 사용할 수 있는건가요?
여러개를 쓸 수 있으면 재밌을 것 같은데...

**Comment by tkddus121** [comment]
아마 하나씩만 사용할 수 있을껄?

**Comment by fuzzythecat** [comment]
투박한 알고리즘이 나올 것 같네요... 
센서 하나로는 상대방 위치의 변화를 파악하기가 힘들 것 같은데,
맵 가장자리를 따라 뱅뱅 돌고있으면 되지 않을까요

상대방이 못찾지 싶은데

**Comment by tkddus121** [comment]
써보니까 소나센서가 감지할수 있는 반경이 넓지 않은 듯
직선 거리에 있는 물체만 인식할 수 있으니까 
도망갈 때 직선으로 움직이기보다 지그재그로 움직이면 좋을 것 같습니다!

**Comment by fuzzythecat** [comment]
가장자리를 따라 움직일 때 생길 수 있는 경우가 어떤 것이 있을까요

뒤  앞
|-->  일때 

상대방이 우리를 뒤에서, 앞에서, 옆에서 때리는 경우가 있을 수 있네요.
옆에서 때리는 경우 상대방이 우리를 왼쪽에서 공격하냐, 오른쪽에서 공격하냐에 따라서
대응이 달라져야할 것 같은데, 센서가 부족해서 구분이 힘들 것 같습니다. 

가장자리를 따라서 움직인다하면 옆에서 공격받는 경우 맵 밖에서 공격받는 경우는 없기 때문에
왼쪽, 오른쪽을 구분하지 않아도 돼서 대응에 수월할 것 같은데, 어떻게 생각하시나요?

**Comment by tkddus121** [comment]
고려해야하는 각이 360도에서 180도로 반으로 줄어들어 괜찮은 것 같습니다
앞, 뒤에서 공격해오는 경우 방향을 전환, 옆에서 공격해오는 경우 방향을 전환하는 
알고리즘을 만들어보면 좋을 것 같습니다

**Comment by fuzzythecat** [comment]
넵넵 해당 알고리즘 문서화 시키겠습니다~
