### ISSUE TITLE
[1차 구상] 알고리즘을 구상합시다

### ISSUE THREAD

**Issue by fuzzythecat** [fuzzythecat/OceanView#6]
Wiki 페이지의 공격모드의 승리조건을 기준으로, 
어떤 알고리즘을 만들어야 이길 수 있을까요?

**Comment by fuzzythecat** [comment]
제자리에서 회전하다가, 상대 로봇을 발견하면 돌진하는 알고리즘은 어떤가요?
센서의 제약이 있어 복잡한 알고리즘은 만들기 어려울 듯 합니다. 
(상대방을 따라가다가, 상대방이 방향을 틀면 왼쪽으로 틀었는지, 오른쪽으로 틀었는지 알 수 없어요)
매번 소나센서에서 상대방을 놓치면 시계방향으로 돌면서 확인하는게 최선일 것 같은데 어떻게 생각하시나요?

**Comment by lukepark327** [comment]
센서를 하나만 사용하는게 제일 걸리네요. 

돌진이 멈추는 조건에 '우리 로봇이 맵 밖으로 나갔을 경우'도 추가해야 할 것 같네요.

**Comment by fuzzythecat** [comment]
그럼 우선 이대로 구현해보도록 해봐요! 1차 구현이니 부족한 부분은 후에 보충하도록 하죠.

**Comment by fuzzythecat** [comment]
상연맨 부탁해~.~
