### ISSUE TITLE
로봇에 어떤 변형을 주어야 할까요 

### ISSUE THREAD

**Issue by tkddus121** [fuzzythecat/OceanView#7]
토론해봅시다

**Comment by fuzzythecat** [comment]
Lego Sumo Bot Competition 2016 EV3
https://www.youtube.com/watch?v=cTG4Mq3OoNo

Lego EV3 Robot Sumo Wrestling BattleBots Challenge
https://www.youtube.com/watch?v=suyPkO0apak

LEGO EV3/NXT Robot SUMO Challenge 2013 @ KTH Kista Part 11
https://www.youtube.com/watch?v=uNfb07P87AY

SFU 2014 EV3 Sumo Bot Battle
https://www.youtube.com/watch?v=3K5p_fkPojM

유튜브에 대회 영상들이 여러개 올라와 있는데 상위 라운드 진출 로봇들을 참고하면 좋을 것 같습니다

**Comment by lukepark327** [comment]
상위권 라운드 진출자들 로봇들을 보니
무게중심이 아래로 가도록 설계하는게 좋을 것 같네요.
아래 부분에서 미는 것이 더 잘 밀릴 것 같습니다.

**Comment by lukepark327** [comment]
그리고 부피가 큰 것보다 
작고 민첩하게 만드는게 더 이점이 있을 것 같네요.
옆으로 크게 만들면 방어모드 때 상대방 로봇에 걸릴 수가 있어서 
컴팩트하게 만드는게 좋을 것 같습니다.

**Comment by fuzzythecat** [comment]
https://www.youtube.com/watch?v=suyPkO0apak
의 16분 경에 나오는 'the cube'는 어떤가요?

**Comment by tkddus121** [comment]
무게중심이 너무 위쪽에 잡혀있어 옆에서 공격 당했을 시 넘어질 것 같은데
행동 불능도 패배 요건에 있어서 불안하네요.

**Comment by fuzzythecat** [comment]
위의 링크에 없는 새로운 영상 추가해봅니다.
https://www.youtube.com/watch?v=I1W88RjAy7s

50분 경에 나오는 로봇 두대가 결승전 진출 로봇인데, 둘 다 디자인이 비슷하네요.

낮은 무게중심과 기동성을 확보하는게 관건일 것 같네요.

50:17에 나오는 왼쪽의 로봇을 모티브로 만드는건 어떨까요?

**Comment by lukepark327** [comment]
좋을 것 같습니다. 이슈 팔게요~
