### ISSUE TITLE
[1차 구현] 구현해봅시다!

### ISSUE THREAD

**Issue by fuzzythecat** [fuzzythecat/OceanView#8]
#5 의 알고리즘을 코드로 구현해봅시다.

**Comment by fuzzythecat** [comment]
시계방향으로 순회를 한다고했을 때, 로봇의 오른편에 터치센서를 달면 좋을 것 같습니다. 
구조 변경이 필요합니다~

**Comment by tkddus121** [comment]
머지완료. 이슈 닫을게요
